version: 2
jobs:
  build_core:
      working_directory: ~/
      docker:
        - image: circleci/android:api-25-alpha
      environment:
            JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Run Tests
            command: ./gradlew clean test --stacktrace
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - store_artifacts:
            path: build/reports
            destination: reports
        - store_test_results:
            path: build/test-results

  build_android:
      working_directory: ~/android
      docker:
        - image: circleci/android:api-25-alpha
      environment:
            JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies
        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Run Tests
            command: ./gradlew clean test lint --stacktrace
        - store_artifacts:
            path: app/build/reports
            destination: reports
        - store_test_results:
            path: app/build/test-results

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_core
      - build_android
